# Generated by Django 3.0.3 on 2020-03-04 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('codigo', models.TextField()),
                ('tipo', models.TextField()),
                ('vestuario', models.BooleanField()),
                ('iluminacion', models.BooleanField()),
                ('cesped', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField()),
                ('empleado', models.TextField()),
                ('fechaReserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Cancha')),
            ],
        ),
    ]
