# Generated by Django 3.0.3 on 2020-03-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200304_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancha', to='blog.Cancha'),
        ),
    ]
